import { history } from '../services';

// export const SET_MONTHLY_BILL = 'SET_MONTHLY_BILL';
// export const SET_USAGE = 'SET_USAGE';
// export const SET_ADDRESS = 'SET_ADDRESS';
// export const SAVE_ADDRESS = 'SAVE_ADDRESS';
// export const NAVIGATE = 'NAVIGATE';
// export const SET_MARKER_POSITION = 'SET_MARKER_POSITION';
// export const RESET_MARKER = 'RESET_MARKER';
// export const START_PROJECT = 'START_PROJECT';
// export const RESET_DONE = 'RESET_DONE';
// export const SET_PANELS = 'SET_PANELS';
// export const GET_RATE = 'GET_RATE';
// export const SET_ANALYSIS = 'SET_ANALYSIS';
// export const EXPORT_RESULT = 'EXPORT_RESULT';
// export const SET_PRICE = 'SET_PRICE';
// export const SET_RATE = 'SET_RATE';
// export const SET_LOADING_RESULTS = 'SET_LOADING_RESULTS';
// export const SET_LOADING_OFFSET = 'SET_LOADING_OFFSET';
// export const LOAD_OFFSET = 'LOAD_OFFSET';
// export const SET_INFO = 'SET_INFO';
// export const SET_DRAWING = 'SET_DRAWING';
// export const SET_DIALOG_VISIBILITY = 'SET_DIALOG_VISIBILITY';
// export const SET_ENERGY_PRODUCTION = 'SET_ENERGY_PRODUCTION';
// export const GET_PROJECT = 'GET_PROJECT';
// export const SET_IMAGE = 'SET_IMAGE';
// export const SET_DRAWID = 'SET_DRAWID';
// export const OPEN_MODAL = 'OPEN_MODAL';
// export const CLOSE_MODAL = 'CLOSE_MODAL';
// export const LOGIN = 'LOGIN';
// export const OPEN_MENU = 'OPEN_MENU';
// export const CLOSE_MENU = 'CLOSE_MENU';
// export const CHANGE_ACTIVE_COMPONENT = 'CHANGE_ACTIVE_COMPONENT';
// export const SET_USER = 'SET_USER';
// export const GET_REFERRED_USERS = 'GET_REFERRED_USERS';
// export const SET_REFERRED_USERS = 'SET_REFERRED_USERS';
// export const SEND_REFERRED_USER = 'SEND_REFERRED_USER';
// export const ADD_REFERRED_USER = 'ADD_REFERRED_USER';
// export const RESET_REFERAL = 'RESET_REFERAL';
// export const CHANGE_MODAL_FIRST_NAME = 'CHANGE_MODAL_FIRST_NAME';
// export const CHANGE_MODAL_LAST_NAME = 'CHANGE_MODAL_LAST_NAME';
// export const CHANGE_MODAL_EMAIL = 'CHANGE_MODAL_EMAIL';
// export const CHANGE_MODAL_PHONE = 'CHANGE_MODAL_PHONE';
// export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
// export const LOGOUT = 'LOGOUT';
// export const CHANGE_FORM_INDEX = 'CHANGE_FORM_INDEX';
// export const CHANGE_LOAN_POSTAL_CODE = 'CHANGE_LOAN_POSTAL_CODE';
// export const CHANGE_LOAN_REGION_CODE = 'CHANGE_LOAN_REGION_CODE';
// export const CHANGE_LOAN_LABEL = 'CHANGE_LOAN_LABEL';
// export const CHANGE_LOAN_CITY = 'CHANGE_LOAN_CITY';
// export const VERIFY_EMAIL = 'VERIFY_EMAIL';
// export const PAY_REFERER = 'PAY_REFERER';
// export const SUBMIT_LOAN_FORM = 'SUBMIT_LOAN_FORM';
// export const DISPLAY_LOAN_DIALOG = 'DISPLAY_LOAN_DIALOG';
// export const HIDE_LOAN_DIALOG = 'HIDE_LOAN_DIALOG';
// export const SET_REFERRED_ID = 'SET_REFERRED_ID';
// export const SEND_LEAD = 'SEND_LEAD';
// export const OPEN_UTILITY_MODAL = 'OPEN_UTILITY_MODAL';
// export const CLOSE_UTILITY_MODAL = 'CLOSE_UTILITY_MODAL';
// export const OPEN_SUCCESS_UTILITY_MODAL = 'OPEN_SUCCESS_UTILITY_MODAL';
// export const CLOSE_SUCCESS_UTILITY_MODAL = 'CLOSE_SUCCESS_UTILITY_MODAL';
// export const ADD_ALERT = 'ADD_ALERT';
// export const REMOVE_ALERT = 'REMOVE_ALERT';
// export const SHOW_ALERT = 'SHOW_ALERT';
// export const HIDE_ALERT = 'HIDE_ALERT';
// export const FORM_CHANGE = 'FORM_CHANGE';
// export const FORM_RESET = 'FORM_RESET';
// export const DISPLAY_LOAN_RATES_TABLE = 'DISPLAY_LOAN_RATES_TABLE';
// export const HIDE_LOAN_RATES_TABLE = 'HIDE_LOAN_RATES_TABLE';
// export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
// export const OPEN_SUCCESS_BANKS_MODAL = 'OPEN_SUCCESS_BANKS_MODAL';
// export const CLOSE_SUCCESS_BANKS_MODAL = 'CLOSE_SUCCESS_BANKS_MODAL';
// export const OPEN_FAIL_BANKS_MODAL = 'OPEN_FAIL_BANKS_MODAL';
// export const CLOSE_FAIL_BANKS_MODAL = 'CLOSE_FAIL_BANKS_MODAL';
// export const OPEN_FORMS_BANKS_MODAL = 'OPEN_FORMS_BANKS_MODAL';
// export const CLOSE_FORMS_BANKS_MODAL = 'CLOSE_FORMS_BANKS_MODAL';
// export const SEND_BANKS = 'SEND_BANKS';
// export const SUBMIT_UTILITY_FORM = 'SUBMIT_UTILITY_FORM';
// export const TEST = 'TEST';
// export const LIGHTSTRAM_RESULT = 'LIGHTSTRAM_RESULT';
// export const LIGHTSTREAM_ERROR = 'LIGHTSTREAM_ERROR';
// export const GET_ALL_USERS = 'GET_ALL_USERS';
// export const USERS_LIST = 'USERS_LIST';
// export const CHANGE_TARGET_USER = 'CHANGE_TARGET_USER';
// export const SPECIFIC_USER_REFERRALS = 'SPECIFIC_USER_REFERRALS';
// export const GET_SPECIFIC_USER = 'GET_SPECIFIC_USER';
export const SET_USER_CURRENT_INPUT = 'SET_USER_CURRENT_INPUT';

function action(type, payload = {}) {
	return { type, ...payload };
}

// export const navigate = (pathname) => {
// 	history.push(pathname);
// 	return action(NAVIGATE, { pathname });
// };
//
// export const setMonthlyBill = (value) => action(SET_MONTHLY_BILL, { value });
// export const setUsage = (value) => action(SET_USAGE, { value });
// export const setAddress = (address) => action(SET_ADDRESS, { address });
// export const saveAddress = () => action(SAVE_ADDRESS);
// export const setMarker = (position) => action(SET_MARKER_POSITION, { position });
// export const startProject = () => action(START_PROJECT);
// export const resetDone = () => action(RESET_DONE);
// export const setPanels = (project, panelGroups) => action(SET_PANELS, { project, panelGroups });
// export const getRate = (state) => action(GET_RATE, { state });
// export const setAnalysis = (project) => action(SET_ANALYSIS, { project });
// export const exportResult = (rawData, image, state, usage, address, imgInfo, id) => action(EXPORT_RESULT, { rawData, image, state, usage, address, imgInfo, id });
// export const setPrice = (price) => action(SET_PRICE, { price });
// export const setRate = (value) => action(SET_RATE, { value });
// export const setLoadingResults = (value) => action(SET_LOADING_RESULTS, { value });
// export const setLoadingOffset = (value) => action(SET_LOADING_OFFSET, { value });
// export const loadOffset = (value) => action(LOAD_OFFSET, { value });
// export const setEnergyProduction = (energyProductionAc) => action(SET_ENERGY_PRODUCTION, { energyProductionAc });
// export const setInfo = (value) => action(SET_INFO, { value });
// export const setDrawing = (drawing) => action(SET_DRAWING, { drawing });
// export const setHelpToolbarDialogVisibility = (visible) => action(SET_DIALOG_VISIBILITY, { visible, dialogType:'HELP_TOOLBAR' });
// export const setHelpOptionDialogVisibility = (visible) => action(SET_DIALOG_VISIBILITY, { visible, dialogType:'HELP_OPTION' });
// export const setLeadFormDialogVisibility = (visible) => action(SET_DIALOG_VISIBILITY, { visible, dialogType:'LEAD_FORM' });
// export const getProject = (drawingId) => action(GET_PROJECT, { drawingId });
// export const setImage = (value) => action(SET_IMAGE, { value });
// export const setDrawId = (id) => action(SET_IMAGE, { id });
// export const openModal = () => action(OPEN_MODAL, {});
// export const closeModal = () => action(CLOSE_MODAL, {});
// export const login = (accessToken) => action(LOGIN, { accessToken });
// export const verifyEmail = (accessToken) => action(VERIFY_EMAIL, { accessToken });
// export const openMenu = () => action(OPEN_MENU, {});
// export const closeMenu = () => action(CLOSE_MENU, {});
// export const changeActiveComponent = (newActiveComponent) => action(CHANGE_ACTIVE_COMPONENT, { newActiveComponent });
// export const setUser = (user) => action(SET_USER, { user });
// export const getReferredUsers = (accessToken) => action(GET_REFERRED_USERS, { accessToken });
// export const setReferredUsers = (referredUsers) => action(SET_REFERRED_USERS, { referredUsers });
// export const addReferredUser = (referredUser) => action(ADD_REFERRED_USER, { referredUser });
// export const sendReferredUser = (accessToken, referredUser) => action(SEND_REFERRED_USER, { accessToken, referredUser });
// export const resetReferal = () => action(RESET_REFERAL, {});
// export const changeModalFirstname = (value) => action(CHANGE_MODAL_FIRST_NAME, { value });
// export const changeModalLastname = (value) => action(CHANGE_MODAL_LAST_NAME, { value });
// export const changeModalEmail = (value) => action(CHANGE_MODAL_EMAIL, { value });
// export const changeModalPhone = (value) => action(CHANGE_MODAL_PHONE, { value });
// export const updateUserInfo = (accessToken, updatedUserInfo) => action(UPDATE_USER_INFO, { accessToken, updatedUserInfo });
// export const logout = () => action(LOGOUT, {});
// export const changeFormIndex = (index) => action(CHANGE_FORM_INDEX, { index });
// export const changeLoanPostalCode = (postalCode) => action(CHANGE_LOAN_POSTAL_CODE, { postal_code:postalCode });
// export const changeLoanRegionCode = (regionCode) => action(CHANGE_LOAN_REGION_CODE, { region_code:regionCode });
// export const changeLoanLabel = (label) => action(CHANGE_LOAN_LABEL, { label });
// export const changeLoanCity = (city) => action(CHANGE_LOAN_CITY, { city });
// export const payReferer = (accessToken, information) => action(PAY_REFERER, { accessToken, information });
// export const submitLoanForm = (loanFormInfo) => action(SUBMIT_LOAN_FORM, { loanFormInfo });
// export const displayLoanDialog = () => action(DISPLAY_LOAN_DIALOG, {});
// export const hideLoanDialog = () => action(HIDE_LOAN_DIALOG, {});
// export const setReferredId = (referredId) => action(SET_REFERRED_ID, { referredId });
// export const sendLead = (lead) => action(SEND_LEAD, { lead });
// export const openUtilityModal = () => action(OPEN_UTILITY_MODAL, {});
// export const closeUtilityModal = () => action(CLOSE_UTILITY_MODAL, {});
// export const openSuccessUtilityModal = () => action(OPEN_SUCCESS_UTILITY_MODAL, {});
// export const closeSuccessUtilityModal = () => action(CLOSE_SUCCESS_UTILITY_MODAL, {});
// export const addAlert = (alert) => action(ADD_ALERT, { alert });
// export const removeAlert = () => action(REMOVE_ALERT, {});
// export const showAlert = () => action(SHOW_ALERT, {});
// export const hideAlert = () => action(HIDE_ALERT, {});
// export const formChange = (what, key, value) => action(FORM_CHANGE, { what, key, value });
// export const formReset = (what) => action(FORM_RESET, { what });
// export const displayLoanRatesTable = () => action(DISPLAY_LOAN_RATES_TABLE, {});
// export const hideLoanRatesTable = () => action(HIDE_LOAN_RATES_TABLE, {});
// export const uploadAvatar = (accessToken, file) => action(UPLOAD_AVATAR, { accessToken, file });
// export const openSuccessBanksModal = () => action(OPEN_SUCCESS_BANKS_MODAL, {});
// export const closeSuccessBanksModal = () => action(CLOSE_SUCCESS_BANKS_MODAL, {});
// export const openFailBanksModal = () => action(OPEN_FAIL_BANKS_MODAL, {});
// export const closeFailBanksModal = () => action(CLOSE_FAIL_BANKS_MODAL, {});
// export const openFormsBanksModal = () => action(OPEN_FORMS_BANKS_MODAL, {});
// export const closeFormsBanksModal = () => action(CLOSE_FORMS_BANKS_MODAL, {});
// export const sendBanks = (banksInfo) => action(SEND_BANKS, { banksInfo });
// export const submitLoan = (loanForm) => action(SUBMIT_LOAN_FORM, { loanForm });
// export const submitUtilityForm = (utilityInfo) => action(SUBMIT_UTILITY_FORM, { utilityInfo });
// export const getAllUsers = (accessToken) => action(GET_ALL_USERS, { accessToken });
// export const changeTargetUser = (auth0Id) => action(CHANGE_TARGET_USER, { auth0Id });
// export const getSpecificUser = (accessToken, targetAuth0UserId) => action(GET_SPECIFIC_USER, { accessToken, targetAuth0UserId });
// export const test = () => action(TEST, {});
export const setUserCurrentInput = (userCurrentInput) => action(SET_USER_CURRENT_INPUT, { userCurrentInput });
